title: Valentino Thomas
email: hello@valentinothomas.com
description: Biomedical Engineering MEng Student | UCL
baseurl: "" # leave empty for root
url: "https://valentinothomas.com"
theme: minima # GitHub Pages built-in theme
